### ISSUE TITLE
Digital Ocean docs page seems outdated compared to the code in docs repo

### ISSUE THREAD

**Issue by karuppiah7890** [hashicorp/packer-plugin-digitalocean#32]
#### Overview of the Issue

Actual site content seems outdated / out of sync compared to the code in this repo. For example, https://www.packer.io/docs/builders/digitalocean#required section shows that droplet sizes can be checked at https://developers.digitalocean.com/documentation/v2/#list-all-sizes but the correct updated URL for that is https://docs.digitalocean.com/reference/api/api-reference/#operation/list_all_sizes which is correctly used in https://github.com/hashicorp/packer-plugin-digitalocean/blob/main/docs-partials/builder/digitalocean/Config-required.mdx code of the docs. So the docs web page seems outdated

#### Reproduction Steps

Check https://www.packer.io/docs/builders/digitalocean#required and compare it with https://github.com/hashicorp/packer-plugin-digitalocean/blob/main/docs-partials/builder/digitalocean/Config-required.mdx content

**Comment by azr** [comment]
I confirm, after releasing this project (and packer.io) this got fixed : https://www.packer.io/plugins/builders/digitalocean#region ! Thanks for reporting and thanks for investigating.
