### ISSUE TITLE
Add ability to make it an Image (instead of a snapshot)

### ISSUE THREAD

**Issue by lowercase00** [hashicorp/packer-plugin-digitalocean#50]
#### Description

Hi, thanks for the plugin.
At the moment this is helpful to make the image a Snapshot.
I guess the way of handle this at the moment would be to build a file, upload to Spaces, and then create the image based on the spaces URL. Would be great if this could be done in one step.

Thanks

**Comment by andrewsomething** [comment]
Hi @lowercase00, 

Sounds like the `digitalocean-import` post-processor is what you are looking for:

https://www.packer.io/plugins/post-processors/digitalocean

It takes a locally built VM-image, uploads it to Spaces, and then imports it as a customer image.

**Comment by lowercase00** [comment]
Hi @andrewsomething, as I understand the `do-import` is a two way process, right?
I have to use the `file` builder in order to use the `do-import`.
Maybe I'm missing something, but I couldn't find a way to make `do-import` leverage an image built with `digitalocean-builder`.
This is a good workaround anyways, thanks!

**Comment by andrewsomething** [comment]
Right. The builder can only produce snapshots and the post-processor can only import an artifact from a previous build step. If you just want to import an existing file, that step can be just be a `file` source. E.g.:

```hcl
source "file" "example" {
  source =  "/path/to/impish-server-cloudimg-amd64.img"
  target =  "ubuntu-img"
}

build {
    sources = ["sources.file.example"]

    post-processor "digitalocean-import" {
        api_token         = "{{user `token`}}"
        spaces_key        = "{{user `key`}}"
        spaces_secret     = "{{user `secret`}}"
        spaces_region     = "nyc3"
        space_name        = "packer-import-bucket"
        image_name        = "ubuntu-21.10-amd64"
        image_description = "Packer import {{timestamp}}"
        image_regions     = ["nyc3"]
        image_tags        = ["packer"]
    }
}
```

Though it can also be the output of a VirtualBox builder, etc.

On the DigitalOcean side, there is not much functional difference between an image and a snapshot. The  distinction is really about the source of the image. Snapshots are based on a running Droplet while custom images are VM images imported from outside of DigitalOcean.

**Comment by lowercase00** [comment]
@andrewsomething thanks a lot.
I indeed misinterpreted DO image/snapshot resources. I though I needed the image to feed the ID to a `libcloud` NodeCreator afterwards. But I just tested DO's. `images` API and indeed shows both images/snapshots on the same route, so that will work perfectly.
Thanks!
